#!/bin/bash

if [ -s "$1" ]; then
    echo "Missing openstack rc path" 
    exit 1
fi

cat <<SUBST
#!/bin/bash
docker create --name ${VOL_CONF_NAME} deploy-heat deploy
docker cp $1 ${VOL_CONF_NAME}:${CONF_PATH}/openrc.sh
docker run -it --rm --volumes-from ${VOL_CONF_NAME} deploy-openstack deploy
SUBST
