#!/bin/bash



cat <<'VARS_OUTER'

#
# Send message and confirm y/n returns true/false
#
confirm () {
    echo
    read -r -p " ${1}: Proceed? [y/n] " response
    case $response in
        [yY][eE][sS]|[yY]) 
            true
            ;;
        *)
            false
            ;;
    esac
}

#
# Find the openstack rc file
#
findrc() {
    while true; do
		echo; 
        read -e -p "Enter the path to your openstack-rc.sh file (ctrl-D to quit): " file && \
            return \$?;
		if [[ ! -s "\$file" ]] ; then
			echo "\$file:  can't read"
		fi
        echo \$file
        return 
    done
}

VARS_OUTER

cat <<SUBST
#!/bin/bash
# Keepgoing var
kg=true

docker inspect ${VOL_CONF_NAME} >& /dev/null
if [ \$? -ne 0 ]; then

	confirm "Create a config container to save settings, have your openstack rc-file ready"  || kg=false
		
    \$kg && RCFILE=\$(findrc)
    [[ \$? != 0 ]] && kg=0

echo RCFILE is \$RCFILE

    \$kg && docker create --name ${VOL_CONF_NAME} deploy-heat deploy

else
	\$kg && confirm "Using pre-existing configuration container ${VOL_CONF_NAME}" || kg=false
fi 

\$kg && docker cp \$RCFILE ${VOL_CONF_NAME}:${CONF_PATH}
\$kg && docker run -it --rm --volumes-from ${VOL_CONF_NAME} deploy-openstack deploy
SUBST
exit
