from ubuntu

RUN 	apt-get -y update &&\	
	apt-get -y install python-urwid python-heatclient python-neutronclient &&\
        apt-get -y clean all 

ARG CONFIG_CONTAINER_NAME
env VOL_CONF_NAME ${CONFIG_CONTAINER_NAME}
ARG	CONFIG_PATH
ENV	CONF_PATH ${CONFIG_PATH}
VOLUME	${CONFIG_PATH}

COPY Files.deploy-heat/* /usr/local/bin/

CMD help
