from ubuntu:wily

run apt-get -y update &&\
    apt-get -y install software-properties-common &&\
    add-apt-repository -y ppa:juju/proposed &&\
    apt-get -y update &&\
    apt-get -y install python-urwid python-heatclient python-novaclient \
        python-neutronclient python-keystoneclient &&\
    apt-get -y install juju juju-quickstart juju-deployer

#ADD help /bin/help

#CMD bash
